[tool.poetry]
name = "ollama-langchain"
version = "0.1.0"
description = ""
authors = ["Manuelji <manueljl22@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
langchain = "^0.0.353"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
